blank_issues_enabled: false
contact_links:
  - name: Support Request / General Question ❓
    url: https://github.com/Codeberg-AsGithubAlternative-buhtz/spielwiese/discussions
    about: Support questions or other topcis not fitting to Feauter Request or Bug Reports.
